name: 'mkhouse-keycloak'

x-common-props: &common-props
  restart: "unless-stopped"
  dns:
    - 1.1.1.1
    - 4.4.4.4
  environment:
    PUID: "1000"
    PGID: "1000"
    TZ: "America/Sao_Paulo"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  extra_hosts:
      - host.docker.internal:host-gateway
  networks:
    stack-net:

services:

  mkhouse-keycloak-db:
    <<: *common-props
    image: "postgres:16-alpine"
    container_name: "mkhouse-keycloak-db"
    hostname: "mkhouse-keycloak-db"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - mkhouse-keycloak-db-data:/var/lib/postgresql/data
    networks:
      stack-net:
      mkhouse-db-net:

  mkhouse-keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: "mkhouse-keycloak"
    hostname: "mkhouse-keycloak"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_USER}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_PASSWORD}"
      DB_VENDOR: "${DB_VENDOR}"
      DB_ADDR: "mkhouse-keycloak-db"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mkhouse-keycloak-data:/opt/keycloak/data
    command: |
      bootstrap-admin \
        user \
          --username:env KEYCLOAK_ADMIN \
          --password:env KEYCLOAK_ADMIN_PASSWORD
    networks:
      stack-net:
      mkhouse-vpc-net:

networks:
  stack-net:
    driver: "bridge"
  mkhouse-vpc-net:
    external: true
  mkhouse-db-net:
    external: true

volumes:
  mkhouse-keycloak-db-data:
    external: true
  mkhouse-keycloak-data:
    external: true

