---
- name: "Publish Keycloak project to remote nodes"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  vars:
    KEYCLOAK_PROJECT: "{{ KEYCLOAK_PROJECT }}"

  tasks:

    - name: "Check if project directory exists"
      stat:
        path: "{{ KEYCLOAK_PROJECT }}"
      register: "project_dir"

    - name: "Create a timestamp variable"
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      when: |
        project_dir.stat.exists

    - name: "Create backup directory if it doesn't exist"
      file:
        path: "{{ KEYCLOAK_PROJECT }}_backup"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      when: |
        project_dir.stat.exists

    - name: "Create a zip backup of the Keycloak project"
      archive:
        path: "{{ KEYCLOAK_PROJECT }}"
        dest: "{{ KEYCLOAK_PROJECT }}_backup/keycloak_backup_{{ timestamp }}.zip"
        format: "zip"
      when: |
        project_dir.stat.exists

- name: "Clean and publish Keycloak project to remote nodes"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  vars:
    KEYCLOAK_PROJECT: "{{ KEYCLOAK_PROJECT }}"

  tasks:

    - name: "Ensure destination directory exists"
      file:
        path: "{{ KEYCLOAK_PROJECT }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Clean the destination directory"
      command: |
        rm -rf {{ KEYCLOAK_PROJECT }}/* {{ KEYCLOAK_PROJECT }}/.[!.]* {{ KEYCLOAK_PROJECT }}/..?*
      ignore_errors: true

    - name: "Copy Keycloak project to remote nodes"
      synchronize:
        src: "{{ ANSIBLE_PROJECT }}/_dropfolder/keycloak/"
        dest: "{{ KEYCLOAK_PROJECT }}"
        delete: true
        recursive: true
        rsync_opts:
          - "--chmod=D0755,F0644"

    - name: "Set permissions on Keycloak project files"
      file:
        path: "{{ KEYCLOAK_PROJECT }}"
        state: "directory"
        recurse: true
        owner: "root"
        group: "root"
        mode: "0755"

- name: "Install Docker"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  tasks:

    - name: "Check if Docker is already installed"
      command: "docker --version"
      register: "docker_installed"
      ignore_errors: true

    - name: "Update package list (Debian/Ubuntu)"
      apt:
        update_cache: true
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Install required packages (Debian/Ubuntu)"
      apt:
        name:
          - "apt-transport-https"
          - "ca-certificates"
          - "curl"
          - "software-properties-common"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Add Docker's official GPG key (Debian/Ubuntu)"
      apt_key:
        url: "https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}/gpg"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Add Docker repository (Debian/Ubuntu)"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }} $(lsb_release -cs) stable"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Update package list after adding Docker repository (Debian/Ubuntu)"
      apt:
        update_cache: true
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Install Docker (Debian/Ubuntu)"
      apt:
        name: "docker-ce"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Update package list (Fedora)"
      dnf:
        update_cache: true
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Install required packages (Fedora)"
      dnf:
        name:
          - "dnf-plugins-core"
        state: "present"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Add Docker repository (Fedora)"
      command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Install Docker (Fedora)"
      dnf:
        name: "docker-ce"
        state: "present"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Ensure Docker service is running and enabled"
      service:
        name: "docker"
        state: "started"
        enabled: "true"
      when: |
        docker_installed.failed

    - name: "Add current user to docker group"
      user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: "true"
      when: |
        docker_installed.failed

- name: "Deploy Keycloak"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true
  vars:
    KEYCLOAK_PROJECT: "{{ KEYCLOAK_PROJECT }}"
    KEYCLOAK_CONTAINER_NAME: "mkhouse-keycloak"

  tasks:

    - name: "Ensure Docker networks exist"
      mkh_ensure_docker_network:
        networks:
          - name: "mkhouse-vpc-net"
          - name: "mkhouse-db-net"

    - name: "Ensure Docker volumes meet expectations"
      mkh_ensure_docker_volume:
        volumes:
          - name: "mkhouse-keycloak-data"
            device:
              path: "/mkh/srv/mkhouse/keycloak-data"
              permissions: '0755'
              puid: '1000'
              pgid: '1000'
          - name: "mkhouse-keycloak-db-data"
            device:
              path: "/mkh/srv/mkhouse/keycloak-db-data"
              permissions: '0755'
              puid: '1000'
              pgid: '1000'

    - name: "Remove existing .env file if it exists"
      file:
        path: "{{ KEYCLOAK_PROJECT }}/.env"
        state: "absent"

    - name: "Generate .env file with token"
      copy:
        dest: "{{ KEYCLOAK_PROJECT }}/.env"
        content: |
          POSTGRES_DB={{ KEYCLOAK_DATABASE_NAME }}
          POSTGRES_USER={{ KEYCLOAK_DATABASE_USER }}
          POSTGRES_PASSWORD={{ KEYCLOAK_DATABASE_PASSWORD }}
          KEYCLOAK_USER={{ KEYCLOAK_USER }}
          KEYCLOAK_PASSWORD={{ KEYCLOAK_PASSWORD }}
          DB_VENDOR={{ KEYCLOAK_DATABASE_VENDOR }}
          DB_DATABASE={{ KEYCLOAK_DATABASE_NAME }}
          DB_USER={{ KEYCLOAK_DATABASE_USER }}
          DB_PASSWORD={{ KEYCLOAK_DATABASE_PASSWORD }}
          HOST_PORT={{ HOST_PORT }}

    - name: "Pull Docker Compose services"
      command: |
        docker compose pull
      args:
        chdir: "{{ KEYCLOAK_PROJECT }}"

    - name: "Stop Docker Compose services"
      command: |
        docker compose down
      args:
        chdir: "{{ KEYCLOAK_PROJECT }}"

    - name: "Start Docker Compose services"
      command: |
        docker compose up -d --force-recreate --remove-orphans --build
      args:
        chdir: "{{ KEYCLOAK_PROJECT }}"

    - name: "Prune unused Docker images"
      command: |
        docker image prune --force

    - name: "Wait for Keycloak to be available"
      uri:
        url: "http://localhost:{{ HOST_PORT }}/auth"
        status_code: "200"
      register: "result"
      until: "result.status == 200"
      retries: 30
      delay: 10

    - name: "Check if Keycloak admin user exists"
      command: |
        docker exec {{ KEYCLOAK_CONTAINER_NAME }} /opt/keycloak/bin/kcadm.sh get users -r master -q username={{ KEYCLOAK_USER }}
      register: "user_check"
      environment:
        KEYCLOAK_USER: "{{ KEYCLOAK_USER }}"
        KEYCLOAK_PASSWORD: "{{ KEYCLOAK_PASSWORD }}"
      when: |
        result.status == 200
      failed_when: |
        user_check.rc not in [0, 1]

    - name: "Create Keycloak admin user"
      command: |
        docker exec {{ KEYCLOAK_CONTAINER_NAME }} /opt/keycloak/bin/kcadm.sh create users -r master -s username={{ KEYCLOAK_USER }} -s enabled=true -s email={{ KEYCLOAK_USER }}@example.com -s firstName=Admin -s lastName=User -s credentials='[{{"type":"password","value":"{{ KEYCLOAK_PASSWORD }}"}}]'
      environment:
        KEYCLOAK_USER: "{{ KEYCLOAK_USER }}"
        KEYCLOAK_PASSWORD: "{{ KEYCLOAK_PASSWORD }}"
      when: |
        result.status == 200 and user_check.rc == 1

- name: "Release Keycloak"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  tasks:

    - name: "Ensure Cloudflared Tunnels"
      mkh_ensure_cfd_tunnel:
        account_id: "{{ CF_ACCOUNT_ID }}"
        api_token: "{{ CF_TUNNEL_API_TOKEN }}"
        tunnel_name: "{{ CF_TUNNEL_NAME }}"
        private_service: "{{ CF_SERVICE }}"
        public_hostname: "{{ CF_HOSTNAME }}"
        zone_id: "{{ CF_ZONE_ID }}"
